### PR TITLE
enable log in nanosdk

### PR DESCRIPTION
**Pull request by OdyWayne**
NNG_DECL int  conf_log_init(int level, int type, char *dir, char *file, uint64_t rotation_sz, size_t rotation_count); 
NNG_DECL int  conf_log_fini();

### CODE REVIEW

**Comment by OdyWayne** [comment]
failed CI for darwin is fixed here --> https://github.com/emqx/NanoSDK/pull/210

**Review by JaylinYu — APPROVED** [review]
I mean log to file , not file API....

**Comment by JaylinYu** [comment]
better removing file.c

**Comment by OdyWayne** [comment]
> I mean log to file , not file API....

these APIs are used for log to file.

**Review by lee-emqx — DISMISSED** [review]

**Review by wanghaEMQ — APPROVED** [review]

**Pull request merged**
