### PR TITLE
Fix `libnng.so` could not link library `libmsquic.so`

### PR DESCRIPTION
**Pull request by alvin1221**

### CODE REVIEW

**Review by wanghaEMQ — COMMENTED** [review]
So... Do you want to make MsQuic an independent library for nanosdk? Cause we would like to make msquic as a part of nanosdk when quic option is on.

**Comment by alvin1221** [comment]
Yeah..

**Comment by JaylinYu** [comment]
not approved
 but gonna merged first, then fix again

**Review by JaylinYu — CHANGES_REQUESTED** [review]
will merge first, but gonna submit a fix then

**Pull request merged**
